#!/usr/bin/env bash
#install nginx and write in it

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo chown -R $USER:$USER /var/www/html
sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
