#!/usr/bin/env bash
#4 bad luck 8 good luck
i=0
while [ $i -le 9 ]
do
	if (( i == 3 )); then
		echo "bad luck"
	elif (( i == 7 )); then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$(( i+1 ))
done
