#!/usr/bin/env bash
#check file status
if (( -e "$school" )); then
	echo "school file exists"
	if (( -s "$school" )); then
		echo "school file is empty"
	else
		echo "school file is not empty"
	if (( -f "$school" )); then
		echo "school is a regular file"
else
	echo "school file does not exist"
